export enum VENDORS_EVENTS {
  VENDOR_CREATE_VENDOR = 'vendor_create_vendor',
  VENDOR_ISSUE_TOKENS = 'vendor_issue_tokens',
  VENDOR_VERIFY_ACCESS_TOKEN = 'vendor_verify_access_token',
  VENDOR_REISSUE_TOKENS = 'vendor_reissue_tokens',
  VENDOR_LOGOUT_VENDOR = 'vendor_logout_vendor',
  VENDOR_READ_VENDOR = 'vendor_read_vendor',
  VENDOR_READ_ALL_VENDORS = 'vendor_read_all_vendors',
  VENDOR_READ_MANY_VENDORS = 'vendor_read_many_vendors',
  VENDOR_UPDATE_VENDOR = 'vendor_update_vendor',
  VENDOR_SUSPEND_VENDOR = 'vendor_suspend_vendor',
  VENDOR_CREATE_USER = 'vendor_create_user',
  VENDOR_READ_USER = 'vendor_read_user',
  VENDOR_READ_ALL_USERS = 'vendor_read_all_users',
  VENDOR_READ_MANY_USERS = 'vendor_read_many_users',
  VENDOR_UPDATE_USER = 'vendor_update_user',
  VENDOR_DELETE_USER = 'vendor_delete_user',
}
